### ISSUE TITLE
Look up team usernames for apps

### ISSUE THREAD

**Issue by TheYellowGamer** [FRC-1721/AdminBot#10]
For example 
Facebook 
Instagram 
Email 
...

**Comment by TheYellowGamer** [comment]
Of means for

**Comment by TheYellowGamer** [comment]
Plz do this it is actually helpful

**Comment by Kredcool** [comment]
isn't this a bad idea because this code is public and anyone with the know how could find our passwords

**Comment by KenwoodFox** [comment]
If we bake passwords in its a bad idea, if we integrate it with FreeIPA (the tool that encrypts our passwords) we open an attack vector into our central password database.

Maybe we can do this safely but tbh, idk, it might be better to install a dedicated service like bitwarden on the robotics server, you know?
