### ISSUE TITLE
make a command to reset the bee movie script 

### ISSUE THREAD

**Issue by NotSimon5673** [FRC-1721/AdminBot#14]
It would be nice to not start from a random point in the script every time we use the command

**Comment by KenwoodFox** [comment]
It starts from 0, and counts up, see here: https://github.com/FRC-1721/AdminBot/blob/6c8b503c61bf7f0cdfe48c51e9f373cd76d15d31/admin_bot/cogs/misc.py#L17

**Comment by NotSimon5673** [comment]
alright that sounds good I can start working on it now.
