### ISSUE TITLE
resetScript fixup

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/AdminBot#16]
resetScript command should have a better name, like `bee reset` (combine into one command) and should also have some sort of confirmation like "set line to 0" or smthn

**Comment by NotSimon5673** [comment]
I've been wondering if there's anywhere I can find an example of what the code for a confirmation would look like? I've looked around a bit but couldn't find anything good for user input on discord bots.

**Comment by KenwoodFox** [comment]
```
[User]: ^bee reset
[Adman]: Succesfully reset the bee-script to 0!```

**Comment by NotSimon5673** [comment]
oh. I thought you meant that you wanted the person typing the command to confirm that they want the script to be reset, my bad. Anyways the code should be good to go then. I guess I'll make a pull request.
