### ISSUE TITLE
Bee movie script saving

### ISSUE THREAD

**Issue by Kredcool** [FRC-1721/AdminBot#22]
While not need it might be a good beginner issue to get the bee movie to remember the line it was on when the bot resets or figure out why its reseting

**Comment by KenwoodFox** [comment]
This is really tricky to do, because docker containers are literally destroyed on reboot, they revert to stock upon starting back up. We can store stuff in a database, i imagine that would be a 1 or 2 week project. Working with a detached seperate database would be the way to go.

**Comment by KenwoodFox** [comment]
Yeah we can do this now but this is dumb
