### ISSUE TITLE
Bot Image reposting

### ISSUE THREAD

**Issue by NotSimon5673** [FRC-1721/AdminBot#24]
Guys this would be moderately entertaining.

When someone replies to an image with the command and specifies a date afterwards, the bot will repost the image at the specified date. alternatively instead of the parameter being a date it could also be a specified amount of time.

we could also have a second parameter for channels but I think that might cause too many problems

I don't think this would be too complicated so I could probably do it myself.

**Comment by KenwoodFox** [comment]
The bot has a database container attached to it, ive not yet poked around but i bet you could implement this using the database for persistant storage :3

as im working on code cleanup for the subteams cog im noticing a bunch of stuff got changed with the way cogs and cog loading works :/ so maybe wait till i iron it all back out.

Whats this for though?~ xD

**Comment by NotSimon5673** [comment]
There's at least 1 practical use for this that I can think of.

it could be used to repost important info at a time when we need it. For example: during a comp

But mostly people will probably use it to  do stupid stuff like make the bot post images at unusual times of the day

also we can probably have the command also do the same thing for text too. Don't really know why I specified just images earlier

Casey pointed out to me that the tetris toaster discord bot has commands that work in a similar way so I can look at them for a rough concept
