### ISSUE TITLE
ban logan from using ^beereset

### ISSUE THREAD

**Issue by NotSimon5673** [FRC-1721/AdminBot#29]
skill issue ¯\_(ツ)_/¯

**Comment by KenwoodFox** [comment]
This can be done yeah, the relevant code is here: https://github.com/FRC-1721/AdminBot/blob/e23062206a56f197ca907af560dc678de53bd6f8/admin_bot/cogs/misc.py#L79

**Comment by NotSimon5673** [comment]
on it

**Comment by NotSimon5673** [comment]
I also am probably going to make it so that the reset command only works on channels that bee works on

**Comment by KenwoodFox** [comment]
This was fixed in an earlier commit i cant be bothered to figure out witch one
